DELIMITER $$

USE `exciting_object`$$

DROP PROCEDURE IF EXISTS `SEQ_GENERATOR`$$

CREATE DEFINER=`eo`@`%` PROCEDURE `SEQ_GENERATOR`(
	IN IN_TABLE_NAME VARCHAR(32),
	OUT OUT_SEQ DOUBLE,
	OUT OUT_PREFIX VARCHAR(6)
    )
BEGIN

	DECLARE _SEQ DOUBLE;
	DECLARE _PREFIX VARCHAR(6);

	UPDATE tb_seq SET seq = seq + 1 WHERE table_name = IN_TABLE_NAME;

	SELECT seq, prefix INTO _SEQ, _PREFIX FROM tb_seq WHERE table_name = IN_TABLE_NAME;

	IF _SEQ > 2176782335 -- SEQ(36진수 6자리) : 0(000000) ~ 2,176,782,335(ZZZZZZ)
	THEN
		SET _SEQ = 0;
		UPDATE tb_seq SET seq = 0 WHERE table_name = IN_TABLE_NAME;
	END IF;
	SET OUT_SEQ = _SEQ;
	SET OUT_PREFIX = _PREFIX;
END$$

DELIMITER ;