spring:
  application:
    name: common
  config:
    import:
    - optional:configserver:http://127.0.0.1:8888/config
    - https://raw.githubusercontent.com/excitingobject/config-server/master/files/common/jpa.mariadb-dev.yml
    - https://raw.githubusercontent.com/excitingobject/config-server/master/files/common/messages-dev.yml
    - https://raw.githubusercontent.com/excitingobject/config-server/master/files/common/rabbitmq-dev.yml
